name: Luce Supervisor (Review Only)

on:
  push:
    branches: [ main ]              # review on real code changes to main
    paths-ignore:
      - '.github/**'                # ignore infra changes
      - 'luce/**'                   # ignore Luce’s own files
      - 'README.md'
  workflow_dispatch: {}             # allow manual runs

concurrency:
  group: luce-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Luce deps (none required; safe fallback)
        working-directory: ./luce
        run: npm ci || npm i || true

      - name: Run Luce Review (Issue-only, no code changes)
        working-directory: ./luce
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run review