name: Luce Supervisor

on:
  push:
    branches: [ main ]           # only main
    paths-ignore:
      - '.github/**'
      - 'luce/**'                # Luce’s own commits won’t retrigger
      - 'README.md'
  schedule:
    - cron: '0 * * * *'          # hourly (adjust later)
  workflow_dispatch:             # allow manual runs

concurrency:
  group: luce-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    if: startsWith(github.ref_name, 'luce/delta-') == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.LUCE_PAT }}   # PAT for pushing/opening PRs

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Syntax check (review.mjs)
        run: node --check luce/review.mjs

      - name: Install deps (Luce)
        working-directory: ./luce
        run: npm ci || npm i

      - name: Run Luce Review (auto-apply)
        working-directory: ./luce
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.LUCE_PAT || github.token }}
        run: npm run review
