name: Luce Supervisor

on:
  push:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
  contents: write
  issues: write
  pull-requests: write

steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      token: ${{ secrets.LUCE_PAT }}   # allows pushing branches

  - name: Run Luce Review (auto-apply)
    working-directory: ./luce
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PREVIEW_URL: ${{ secrets.PREVIEW_URL }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_TOKEN: ${{ secrets.LUCE_PAT }}   # used by API calls to open PRs
    run: npm run review

